[package]
name                 = "streamswap-interface"
description          = "Streamswap rust generated interfacts with cw-orch"
authors.workspace    = true
edition.workspace    = true
homepage.workspace   = true
license.workspace    = true
repository.workspace = true
version.workspace    = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw-orch               = { workspace = true }
streamswap-types      = { workspace = true }
streamswap-controller = { workspace = true }

[lints]
workspace = true
