/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./StreamSwapController.types";
import * as _1 from "./StreamSwapController.client";
import * as _2 from "./StreamSwapController.message-composer";
import * as _3 from "./StreamSwapStream.types";
import * as _4 from "./StreamSwapStream.client";
import * as _5 from "./StreamSwapStream.message-composer";
export namespace contracts {
  export const StreamSwapController = { ..._0,
    ..._1,
    ..._2
  };
  export const StreamSwapStream = { ..._3,
    ..._4,
    ..._5
  };
}