/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export type Timestamp = Uint64;
export type Uint64 = string;
export type UncheckedDenom = {
  native: string;
} | {
  cw20: string;
};
export type Schedule = "saturating_linear" | {
  piecewise_linear: [number, Uint128][];
};
export interface InstantiateMsg {
  create_pool?: CreatePool | null;
  end_time: Timestamp;
  in_denom: string;
  name: string;
  out_asset: Coin;
  start_time: Timestamp;
  stream_admin: string;
  threshold?: Uint128 | null;
  treasury: string;
  url?: string | null;
  vesting?: InstantiateMsg1 | null;
}
export interface CreatePool {
  msg_create_pool: MsgCreateConcentratedPool;
  out_amount_clp: Uint128;
}
export interface MsgCreateConcentratedPool {
  denom0: string;
  denom1: string;
  sender: string;
  spread_factor: string;
  tick_spacing: number;
  [k: string]: unknown;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export interface InstantiateMsg1 {
  denom: UncheckedDenom;
  description?: string | null;
  owner?: string | null;
  recipient: string;
  schedule: Schedule;
  start_time?: Timestamp | null;
  title: string;
  total: Uint128;
  unbonding_duration_seconds: number;
  vesting_duration_seconds: number;
}
export type ExecuteMsg = {
  update_stream: {};
} | {
  update_operator: {
    new_operator?: string | null;
  };
} | {
  subscribe: {
    operator?: string | null;
    operator_target?: string | null;
  };
} | {
  withdraw: {
    cap?: Uint128 | null;
    operator_target?: string | null;
  };
} | {
  update_position: {
    operator_target?: string | null;
  };
} | {
  finalize_stream: {
    new_treasury?: string | null;
  };
} | {
  exit_stream: {
    operator_target?: string | null;
    salt?: Binary | null;
  };
} | {
  pause_stream: {};
} | {
  withdraw_paused: {
    cap?: Uint128 | null;
    operator_target?: string | null;
  };
} | {
  exit_cancelled: {
    operator_target?: string | null;
  };
} | {
  resume_stream: {};
} | {
  cancel_stream: {};
} | {
  cancel_stream_with_threshold: {};
};
export type Binary = string;
export type QueryMsg = {
  params: {};
} | {
  stream: {};
} | {
  position: {
    owner: string;
  };
} | {
  list_positions: {
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  average_price: {};
} | {
  last_streamed_price: {};
} | {
  threshold: {};
};
export type Decimal = string;
export interface AveragePriceResponse {
  average_price: Decimal;
}
export interface LatestStreamedPriceResponse {
  current_streamed_price: Decimal;
}
export type Decimal256 = string;
export type Addr = string;
export interface PositionsResponse {
  positions: PositionResponse[];
}
export interface PositionResponse {
  in_balance: Uint128;
  index: Decimal256;
  last_updated: Timestamp;
  operator?: Addr | null;
  owner: string;
  pending_purchase: Decimal256;
  purchased: Uint128;
  shares: Uint128;
  spent: Uint128;
}
export interface Params {
  accepted_in_denoms: string[];
  exit_fee_percent: Decimal;
  fee_collector: Addr;
  min_seconds_until_start_time: number;
  min_stream_seconds: number;
  protocol_admin: Addr;
  stream_creation_fee: Coin;
  stream_swap_code_id: number;
  vesting_code_id: number;
}
export type Status = ("active" | "finalized" | "paused" | "cancelled") | "waiting";
export interface StreamResponse {
  current_streamed_price: Decimal;
  dist_index: Decimal256;
  end_time: Timestamp;
  in_denom: string;
  in_supply: Uint128;
  last_updated: Timestamp;
  out_asset: Coin;
  out_remaining: Uint128;
  pause_date?: Timestamp | null;
  shares: Uint128;
  spent_in: Uint128;
  start_time: Timestamp;
  status: Status;
  stream_admin: string;
  treasury: string;
  url?: string | null;
}