/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Decimal = string;
export type Uint128 = string;
export interface InstantiateMsg {
  denom: UncheckedDenom;
  description?: string | null;
  owner?: string | null;
  recipient: string;
  schedule: Schedule;
  start_time?: Timestamp | null;
  title: string;
  total: Uint128;
  unbonding_duration_seconds: number;
  vesting_duration_seconds: number;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export type ExecuteMsg = {
  update_params: {
    accepted_in_denoms?: string[] | null;
    exit_fee_percent?: Decimal | null;
    fee_collector?: string | null;
    min_seconds_until_start_time?: number | null;
    min_stream_seconds?: number | null;
    stream_creation_fee?: Coin | null;
  };
} | {
  create_stream: {
    msg: CreateStreamMsg;
  };
} | {
  freeze: {};
};
export type Timestamp = Uint64;
export type Uint64 = number;
export type UncheckedDenom = {
  native: string;
} | {
  cw20: string;
};
export type Schedule = "saturating_linear" | {
  piecewise_linear: [number, Uint128][];
};
export interface CreateStreamMsg {
  create_pool?: CreatePool | null;
  end_time: Timestamp;
  in_denom: string;
  name: string;
  out_asset: Coin;
  start_time: Timestamp;
  stream_admin: string;
  threshold?: Uint128 | null;
  treasury: string;
  url?: string | null;
  vesting?: InstantiateMsg | null;
}
export interface CreatePool {
  msg_create_pool: MsgCreateConcentratedPool;
  out_amount_clp: Uint128;
}
export interface MsgCreateConcentratedPool {
  denom0: string;
  denom1: string;
  sender: string;
  spread_factor: string;
  tick_spacing: number;
  [k: string]: unknown;
}
export type QueryMsg = {
  params: {};
} | {
  freezestate: {};
} | {
  last_stream_id: {};
};
export type Boolean = boolean;
export type Addr = string;
export interface Params {
  accepted_in_denoms: string[];
  exit_fee_percent: Decimal;
  fee_collector: Addr;
  min_seconds_until_start_time: number;
  min_stream_seconds: number;
  protocol_admin: Addr;
  stream_creation_fee: Coin;
  stream_swap_code_id: number;
  vesting_code_id: number;
}