[package]
name          = "streamswap-utils"
description   = "Helpers and utilities for StreamSwap smart contracts"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
repository    = { workspace = true }
homepage      = { workspace = true }

[features]
# for quicker tests, cargo test --lib

[lints]
workspace = true

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true }
cw-utils        = { workspace = true }
thiserror       = { workspace = true }
